config/routes.rb
Rails.application.routes.draw do
  #root "main#index"
  root "users#recognize"
  get 'main/index'
  resources :users do
    get :recognize, on: :collection
    post :identify, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'digest'
require 'baidu_face'

class User < ApplicationRecord
  API = BaiduFace.new('I7GjQK3oFkfGOZXemaBcfGeA', '6LKW0PCFbInRwfOavMyjkErGDPcrXAlz')

  validates_presence_of :name
  validates_presence_of :image

  attr_accessor :file

  before_validation :set_image
  before_save :save_image_file
  after_save :register_user

  def save_image_file
    File.open("#{Rails.root}/public/uploads/#{self.image}", "wb+") do |f|
      f.write file_content
    end
  end

  def set_image
    self.image = "#{calc_md5}.#{file.original_filename.split('.').last}"
  end

  def calc_md5
    Digest::MD5.hexdigest(file_content)
  end

  def file_content
    file.rewind
    file.read
  end

  ## options: {uid: uid, group_id: group_id, image: image, user_info: user_info, action_type: action_type}
  def register_user
    ret = API.add(uid: self.id.to_s, group_id: "default", image: Base64.encode64(file_content), user_info: self.name, action_type: "append")
    binding.pry
  end

  # 人脸集合中查找
  # options: {image: image, group_id: group_id, ext_filelds: ext_fields, user_top_num: user_top_num}
  def self.identify(options)
    API.identify options
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new({name: params[:name], file: params[:file]})

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update({name: params[:name], file: params[:file]})
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recognize
  end

  # 人脸集合中查找
  # options: {image: image, group_id: group_id, ext_filelds: ext_fields, user_top_num: user_top_num}
  def identify
    info = User.identify({image: Base64.encode64(params[:image].read), group_id: "default", ext_fields: {}, user_top_num: 1})

    render :json => info
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>FindFace</title>
  <%= csrf_meta_tags %>

  <!-- Bootstrap -->
  <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet"
        href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">


  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="container-fluid" style="margin: 0;">
  <%= yield %>
</div>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>

app/views/main/index.html.erb
<div class="row" style="padding: 0;">
  <div class="col-lg-6 col-md-6 col-sm-12 identify">
    <span class="glyphicon glyphicon-camera"></span>
    <p>
      <%= link_to "识别人脸", recognize_users_path%>
    </p>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-12 register">
    <span class="glyphicon glyphicon-user"></span>
    <p>
      <%= link_to "注册人脸", new_user_path%>
    </p>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-sm-12">
    <%= form_with(model: user, local: true, class: "form") do |form| %>
        <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, "名称" %>
          <%= form.text_field :name, id: :user_name, class: "form-control" %>
        </div>

        <div class="field">
          <%= form.label :image, "头像" %>
          <%= form.file_field :image, id: :user_image, type: "file" %>
        </div>

        <br>
        <div class="actions">
          <input type="button" class="btn btn-success btn-submit" value="submit">
        </div>
    <% end %>
  </div>
</div>

<script>
  jQuery(document).ready(function ($) {
      var image_data;

      $('#user_image').on('change', function(e){
          const file = e.target.files[0];
          if (!file) {
              return;
          }
          new ImageCompressor(file, {
              quality: .6,
              success(result) {
                  image_data = result;
              },
              error(e) {
                  console.log(e.message);
              },
          });
      });

      $(".btn-submit").on("click", function () {
          const formData = new FormData();
          formData.append('file', image_data, image_data.name);
          formData.append('name', $("#user_name").val());

          $.ajax({
              url: "/users.json",
              type: "post",
              data: formData,
              processData:false,
              contentType:false,
              success:function(data){
                  console.log(data);
                  window.location.href = "/users";
              }
          });

      })
  });
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= image_tag "/uploads/#{user.image}", size: "50x50" %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>新建用户</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/recognize.html.erb
<style>
  *{margin: 0;padding: 0;}
  li{list-style-type: none;}
  a,input{outline: none;-webkit-tap-highlight-color:rgba(0,0,0,0);}
  #choose{display: none;}
  canvas{width: 100%;border: 1px solid #000000;}
  .btn-center{display: block;text-align: center;cursor: pointer; margin: 10px;}
  .touch{background-color: #ddd;}
  .img-list{margin: 10px 5px;}
  .img-list li{position: relative;display: inline-block;width: 100px;height: 100px;margin: 5px 5px 20px 5px;border: 1px solid rgb(100,149,198);background: #fff no-repeat center;background-size: cover;}
  #img-preview{
    position: relative;
    display: block;
    width: 300px;
    height: 300px;
    margin: 30px auto;
    border: 0;
    padding-top: 80px;
    background: #eee no-repeat center;
    background-size: cover;
  }
  .progress{position: absolute;width: 100%;height: 20px;line-height: 20px;bottom: 0;left: 0;background-color:rgba(100,149,198,.5);}
  .progress span{display: block;width: 0;height: 100%;background-color:rgb(100,149,198);text-align: center;color: #FFF;font-size: 13px;}
  .size{position: absolute;width: 100%;height: 15px;line-height: 15px;bottom: -18px;text-align: center;font-size: 13px;color: #666;}
  .tips{display: block;text-align:center;font-size: 13px;margin: 10px;color: #999;}
  .pic-list{margin: 10px;line-height: 18px;font-size: 13px;}
  .pic-list a{display: block;margin: 10px 0;}
  .pic-list a img{vertical-align: middle;max-width: 30px;max-height: 30px;margin: -4px 0 0 10px;}
  .ocr-text {width: 100%; border: 1px solid gainsboro; margin: 10px; padding: 5px;}
</style>

<input type="file" id="choose" accept="image/*">
<div id="img-preview" >
  <h1 class="text-center">Find Face</h1>
</div>
<div id="recog_text" hidden style="word-break: break-all; "></div>

<a id="upload" class="btn btn-lg btn-default btn-center">上传图片</a>
<!--a id="btn_ocr" class="btn btn-lg btn-success btn-center" href="javascript:void(0);">识别文字</a-->
<span class="tips">只允许上传jpg、png及gif</span>

<script>
    var filechooser = document.getElementById("choose");
    //    用于压缩图片的canvas
    var canvas = document.createElement("canvas");
    var ctx = canvas.getContext('2d');
    //    瓦片canvas
    var tCanvas = document.createElement("canvas");
    var tctx = tCanvas.getContext("2d");
    var maxsize = 100 * 1024;
    $("#upload").on("click", function() {
        filechooser.click();
    })
        .on("touchstart", function() {
            $(this).addClass("touch")
        })
        .on("touchend", function() {
            $(this).removeClass("touch")
        });
    filechooser.onchange = function() {
        if (!this.files.length) return;
        var files = Array.prototype.slice.call(this.files);
        if (files.length > 9) {
            alert("最多同时只可上传9张图片");
            return;
        }
        files.forEach(function(file, i) {
            if (!/\/(?:jpeg|png|gif)/i.test(file.type)) return;
            var reader = new FileReader();
            //var li = document.createElement("div");
            var li = document.getElementById("img-preview");
            //  获取图片大小
            var size = file.size / 1024 > 1024 ? (~~(10 * file.size / 1024 / 1024)) / 10 + "MB" : ~~(file.size / 1024) + "KB";
            //li.innerHTML = '<div class="progress"><span></span></div><div class="size">' + size + '</div>';
            //$("#img-preview").append($(li));
            $(li).html('<div class="progress"><span></span></div><div class="size">' + size + '</div>');
            reader.onload = function() {
                var result = this.result;
                var img = new Image();
                img.src = result;
                $(li).css("background-image", "url(" + result + ")");
                //如果图片大小小于100kb，则直接上传
                if (result.length <= maxsize) {
                    img = null;
                    upload(result, file.type, $(li));
                    return;
                }
//      图片加载完毕之后进行压缩，然后上传
                if (img.complete) {
                    callback();
                } else {
                    img.onload = callback;
                }
                function callback() {
                    var data = compress(img);
                    upload(data, file.type, $(li));
                    img = null;
                }
            };
            reader.readAsDataURL(file);
        })
    };
    //    使用canvas对大图片进行压缩
    function compress(img) {
        var initSize = img.src.length;
        var width = img.width;
        var height = img.height;
        //如果图片大于四百万像素，计算压缩比并将大小压至400万以下
        var ratio;
        if ((ratio = width * height / 4000000) > 1) {
            ratio = Math.sqrt(ratio);
            width /= ratio;
            height /= ratio;
        } else {
            ratio = 1;
        }
        canvas.width = width;
        canvas.height = height;
//        铺底色
        ctx.fillStyle = "#fff";
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        //如果图片像素大于100万则使用瓦片绘制
        var count;
        if ((count = width * height / 1000000) > 1) {
            count = ~~(Math.sqrt(count) + 1); //计算要分成多少块瓦片
//            计算每块瓦片的宽和高
            var nw = ~~(width / count);
            var nh = ~~(height / count);
            tCanvas.width = nw;
            tCanvas.height = nh;
            for (var i = 0; i < count; i++) {
                for (var j = 0; j < count; j++) {
                    tctx.drawImage(img, i * nw * ratio, j * nh * ratio, nw * ratio, nh * ratio, 0, 0, nw, nh);
                    ctx.drawImage(tCanvas, i * nw, j * nh, nw, nh);
                }
            }
        } else {
            ctx.drawImage(img, 0, 0, width, height);
        }
        //进行最小压缩
        var ndata = canvas.toDataURL('image/jpeg', 0.3);
        console.log('压缩前：' + initSize);
        console.log('压缩后：' + ndata.length);
        console.log('压缩率：' + ~~(100 * (initSize - ndata.length) / initSize) + "%");
        tCanvas.width = tCanvas.height = canvas.width = canvas.height = 0;
        return ndata;
    }
    //    图片上传，将base64的图片转成二进制对象，塞进formdata上传
    function upload(basestr, type, $li) {
        var text = window.atob(basestr.split(",")[1]);
        var buffer = new Uint8Array(text.length);
        var pecent = 0, loop = null;
        for (var i = 0; i < text.length; i++) {
            buffer[i] = text.charCodeAt(i);
        }
        var blob = getBlob([buffer], type);
        var xhr = new XMLHttpRequest();
        var formdata = getFormData();
        formdata.append('image', blob);
        xhr.open('post', '<%=identify_users_path%>');
        xhr.onreadystatechange = function() {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var jsonData = JSON.parse(xhr.responseText);
                console.log(jsonData);

                if(jsonData['result'][0]['user_info'] == '刘颖' && jsonData['result'][0]['scores'] > 75)
                {
                    alert('老婆， 节日快乐！！！ 爱你 ^_^');
                }
                else if(jsonData['result'][0]['user_info'] == 'liteng' && jsonData['result'][0]['scores'] > 75)
                {
                    alert('李螣大人... 您想干嘛！！！');
                }
                else
                {
                    alert("who  are you ?");
                }

                //$("#recog_text").text(xhr.responseText);
                //$("#recog_text").show();
                var imagedata = jsonData || {};
                var text = '上传成功';
                if(imagedata.image_name != undefined){
                    $("#btn_ocr").data("image_name", imagedata.image_name);
                }

                clearInterval(loop);
                //当收到该消息时上传完毕
                $li.find(".progress span").animate({'width': "100%"}, pecent < 95 ? 200 : 0, function() {
                    $(this).html(text);
                });
                if (!imagedata.path) return;
                $(".pic-list").append('<a href="' + imagedata.path + '">' + imagedata.name + '（' + imagedata.size + '）<img src="' + imagedata.path + '" /></a>');
            }
        };
        //数据发送进度，前50%展示该进度
        xhr.upload.addEventListener('progress', function(e) {
            if (loop) return;
            pecent = ~~(100 * e.loaded / e.total) / 2;
            $li.find(".progress span").css('width', pecent + "%");
            if (pecent == 50) {
                mockProgress();
            }
        }, false);
        //数据后50%用模拟进度
        function mockProgress() {
            if (loop) return;
            loop = setInterval(function() {
                pecent++;
                $li.find(".progress span").css('width', pecent + "%");
                if (pecent == 99) {
                    clearInterval(loop);
                }
            }, 100)
        }
        xhr.send(formdata);
    }
    /**
     * 获取blob对象的兼容性写法
     * @param buffer
     * @param format
     * @returns {*}
     */
    function getBlob(buffer, format) {
        try {
            return new Blob(buffer, {type: format});
        } catch (e) {
            var bb = new (window.BlobBuilder || window.WebKitBlobBuilder || window.MSBlobBuilder);
            buffer.forEach(function(buf) {
                bb.append(buf);
            });
            return bb.getBlob(format);
        }
    }
    /**
     * 获取formdata
     */
    function getFormData() {
        var isNeedShim = ~navigator.userAgent.indexOf('Android')
            && ~navigator.vendor.indexOf('Google')
            && !~navigator.userAgent.indexOf('Chrome')
            && navigator.userAgent.match(/AppleWebKit\/(\d+)/).pop() <= 534;
        return isNeedShim ? new FormDataShim() : new FormData()
    }
    /**
     * formdata 补丁, 给不支持formdata上传blob的android机打补丁
     * @constructor
     */
    function FormDataShim() {
        console.warn('using formdata shim');
        var o = this,
            parts = [],
            boundary = Array(21).join('-') + (+new Date() * (1e16 * Math.random())).toString(36),
            oldSend = XMLHttpRequest.prototype.send;
        this.append = function(name, value, filename) {
            parts.push('--' + boundary + '\r\nContent-Disposition: form-data; name="' + name + '"');
            if (value instanceof Blob) {
                parts.push('; filename="' + (filename || 'blob') + '"\r\nContent-Type: ' + value.type + '\r\n\r\n');
                parts.push(value);
            }
            else {
                parts.push('\r\n\r\n' + value);
            }
            parts.push('\r\n');
        };
        // Override XHR send()
        XMLHttpRequest.prototype.send = function(val) {
            var fr,
                data,
                oXHR = this;
            if (val === o) {
                // Append the final boundary string
                parts.push('--' + boundary + '--\r\n');
                // Create the blob
                data = getBlob(parts);
                // Set up and read the blob into an array to be sent
                fr = new FileReader();
                fr.onload = function() {
                    oldSend.call(oXHR, fr.result);
                };
                fr.onerror = function(err) {
                    throw err;
                };
                fr.readAsArrayBuffer(data);
                // Set the multipart content type and boudary
                this.setRequestHeader('Content-Type', 'multipart/form-data; boundary=' + boundary);
                XMLHttpRequest.prototype.send = oldSend;
            }
            else {
                oldSend.call(this, val);
            }
        };
    }

    $("#btn_ocr").on("click", function () {
        if($(this).attr("disabled") != undefined){
            return;
        }

        var image_name = $(this).data("image_name");
        if(!!image_name){
            $("#btn_ocr").attr("disabled", "disabled");
            $.get("<%=recognize_users_path%>", {image_name: image_name}, function (data) {
                $("#recog_text").text(data.content);
                $("#recog_text").toggle("show")
                $("#btn_ocr").removeAttr("disabled");
            })
        }
        else{
            alert("请先上传图片！")
        }
    });
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user.image %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>